# Generated by Django 2.2.5 on 2019-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop', models.CharField(max_length=50)),
                ('CropVariety', models.CharField(max_length=50)),
                ('Quantity', models.PositiveIntegerField(default=None)),
                ('DeliveryDate', models.DateField()),
                ('AdvanceDate', models.DateField(null=True)),
                ('ProductionMode', models.CharField(max_length=50)),
                ('ContractPrice', models.FloatField(default=None)),
                ('advance', models.FloatField(default=None)),
            ],
        ),
    ]
